version: '3.8'

services:

 mariadb:
  container_name: mariadb
  restart: unless-stopped
  build:
   context: requierments/mariadb
   dockerfile: Dockerfile
  image: mariadb:inception
  volumes:
    - mariadb:/var/lib/mysql
  ports:
   - 3306:3306
  environment:
   env_file: .env
  networks:
   - inception

 wordpress:
  container_name: wordpress
  restart: unless-stopped
  build:
    context: requierments/wordpress
    dockerfile: Dockerfile
  image: wordpress:inception
  volumes:
    - wp:/var/www/wp
  env_file: .env
  networks:
    - inception
  depends_on:
    mariadb:
      condition: service_started

 nginx:
  container_name: nginx
  restart: unless-stopped
  build:
   context: requierments/nginx
   dockerfile: Dockerfile
  image: nginx:inception
  volumes:
    - wordpress:/var/www/wp
  ports:
   - 443:443
  networks:
    - inception
  depends_on:
    wordpress:
      condition: service_started

networks:
 inception:
  name: inception
  driver: bridge

volumes:

  mariadb:
    driver: local
    driver_opts:
      device: /home/${USER}/data/mariadb
      type: bind

  wp:
    driver: local
    driver_opts:
      device: /home/${USER}/data/wp
      type: bind
