services:

 mariadb:
  container_name: mariadb
  restart: unless-stopped
  build:
   context: requirements/mariadb
   dockerfile: Dockerfile
  image: mariadb:inception
  volumes:
    - mariadb_data:/var/lib/mysql
  env_file: .env
  networks:
   - inception

 nginx:
  container_name: nginx
  restart: unless-stopped
  build:
   context: requirements/nginx
   dockerfile: Dockerfile
  image: nginx:inception
  volumes:
    - wp_data:/var/www/html
  ports:
   - 443:443
  networks:
   - inception
  depends_on:
    wordpress:
      condition: service_started
      
 wordpress:
  container_name: wordpress
  restart: unless-stopped
  build:
    context: requirements/wordpress
    dockerfile: Dockerfile
  image: wordpress:inception
  volumes:
    - wp_data:/var/www/html
  env_file: .env
  networks:
    - inception
  depends_on:
    mariadb:
      condition: service_started

networks:
 inception:
  driver: bridge

volumes:

  mariadb_data:
    name: DB
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

  wp_data:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
